server.port=${SERVER_PORT:8081}

spring.flyway.locations=classpath:db/migration/master
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.mvc.servlet.path=/api

app.datasource.master.host=${MASTER_DB_HOST}
app.datasource.master.port=${MASTER_DB_PORT}
app.datasource.master.database=${MASTER_DB_NAME}
app.datasource.master.username=${MASTER_DB_USERNAME}
app.datasource.master.password=${MASTER_DB_PASSWORD}

app.datasource.template.host=${TEMPLATE_DB_HOST}
app.datasource.template.port=${TEMPLATE_DB_PORT}
app.datasource.template.database=${TEMPLATE_DB_NAME}
app.datasource.template.username=${TEMPLATE_DB_USERNAME}
app.datasource.template.password=${TEMPLATE_DB_PASSWORD}

app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.issuer=${JWT_ISSUER:az-erp-backend}
app.security.jwt.expiration-hours=${JWT_EXPIRATION_HOURS:8}
