server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/az_erp_master_db
spring.datasource.username=postgres
spring.datasource.password=14114
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.locations=classpath:db/migration/master


spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.mvc.servlet.path=/api

app.datasource.template.host=localhost
app.datasource.template.port=5432
app.datasource.template.database=az_erp_template
app.datasource.template.username=postgres
app.datasource.template.password=14114


app.datasource.master.host=localhost
app.datasource.master.port=5432
app.datasource.master.database=az_erp_master_db
app.datasource.master.username=postgres
app.datasource.master.password=14114